version: "3.9"

services:
  api:
    image: prostakov/notes-api:latest
    environment:
      ConnectionStrings:Database: "Server=db;Database=$DATABASE_NAME;User=$DATABASE_USER;Password=$DATABASE_PASSWORD;MultipleActiveResultSets=true"
    ports:
      - "9410:80"
    restart: always
    depends_on:
      - db
    healthcheck:
      test: wget --no-verbose http://localhost:80/healthcheck || exit 1
      interval: 10s
      timeout: 3s
      retries: 600
      start_period: 10s
  db:
    image: prostakov/mssql:latest
    volumes:
      - mssqldata:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: $DATABASE_SA_PASSWORD
      DATABASE: $DATABASE_NAME
      USER: $DATABASE_USER
      PASSWORD: $DATABASE_PASSWORD
    ports:
      - "9101:1433"
    restart: always
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -b -S localhost -U sa -P $DATABASE_SA_PASSWORD -Q "SELECT * FROM [$DATABASE_NAME].[INFORMATION_SCHEMA].[TABLES]" || exit 1
      interval: 10s
      timeout: 3s
      retries: 600
      start_period: 10s

volumes:
  mssqldata: